# cog/docker-compose.yml
version: '3.6'

services:
  gin_cog:
    image: hub.foundries.io/ew2023-customer1/cog:latest
    restart: always
    tty: true
    network_mode: "host"
    command: "http://localhost:3000/d/COSuPqEGz/2jcie-bu01-environment-sensor?orgId=1&refresh=30s&kiosk=1"
    tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /tmp
    volumes:
      - /run/user/63:/run/user/63
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 226:* rmw'
    environment:
      WAYLAND_USER: "weston"
      XDG_RUNTIME_DIR: "/run/user/63"
      WAYLAND_DISPLAY: "wayland-1"
      TIMER: "0"
      COG_PLATFORM_WL_VIEW_FULLSCREEN: "0"
