# /lmp-flutter-qemuarm64-secureboot/docker-compose.yml
# https://source.foundries.io/factories/lmp-demo/lmp-manifest.git/?h=lmp-flutter
# docker import lmp-factory-image-raspberrypi4-64.tar.bz2 munoz0raul/lmp-flutter-qemuarm64-secureboot
# docker push munoz0raul/lmp-flutter-qemuarm64-secureboot
version: '3.6'

services:
  lmp-flutter-qemuarm64-secureboot:
    image: munoz0raul/lmp-flutter-qemuarm64-secureboot:target-63
    restart: always
    tty: true
    network_mode: "host"
    entrypoint: [ "/bin/bash" ]
    command: [ "/usr/share/flutter/flutter.sh" ]
    tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /tmp
    volumes:
      - /run/user/63:/run/user/63
      - /dev/dri:/dev/dri
      - ./flutter.sh:/usr/share/flutter/flutter.sh
    device_cgroup_rules:
      - 'c 226:* rmw'
    environment:
      WAYLAND_USER: "weston"
      XDG_RUNTIME_DIR: "/run/user/63"
      WAYLAND_DISPLAY: "wayland-1"
      TIMER: "0"
      WIDTH: "1280"
      HEIGHT: "768"
